In [1]:
from numpy import *

In [2]:
a = array([2,3,4])

In [3]:
a

array([2, 3, 4])

In [4]:
a.dtype

dtype('int64')

In [5]:
b = array([1.2,3.5, 5.1])

In [6]:
b.dtype

dtype('float64')

In [8]:
c = array([(1.5, 2, 3), (4,5,6)])

In [10]:
c.dtype;c

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [11]:
d = zeros((3,4))

In [12]:
d

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [13]:
d.dtype.itemsize

8

In [15]:
e = ones((2,3,4), dtype=int16);e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
f= empty((2,3)); f

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [19]:
r = arange(10,30, 5);r # range with step of 5

array([10, 15, 20, 25])

In [21]:
reshape = arange(12).reshape(4,3);reshape

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
print arange(10000).reshape(100,100)

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [23]:
student= dtype({'names':['name', 'age', 'weight'], 'formats':['S32', 'i','f']}, align = True) # 自定义数据结构类型

In [31]:
a = arange(9).reshape(3,3)

print "=====a  \n",a
b = 2 * a
print "====== 2 * a"
print b
con = concatenate((a,b), axis = 1)
print "====== concatenate, axis = 1"
print con
con = concatenate((a,b), axis = 0)
print "====== concatenate, axis = 0\n",con


hs = hstack((a,b))
print "====== hstack( a,b)\n", hs

vs = vstack((a,b))
print "====== vstack( a,b)\n", vs


ds = dstack((a,b)) # 这个比较特殊，这是新加了一维数据，
# 相当于多了一个平面，然后把每个平面的同一个(x,y)
print "====== dstack( a,b)\n", ds

=====a  
[[0 1 2]
 [3 4 5]
 [6 7 8]]
====== 2 * a
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
====== concatenate, axis = 1
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
====== concatenate, axis = 0
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
====== hstack( a,b)
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
====== vstack( a,b)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
====== dstack( a,b)
[[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]]


In [33]:
one = arange(2);print "======one\n", one
two = one + 2; print "======two\n",two
print "===row_stack one, two\n",row_stack((one, two))
print "===column_stack one, two\n",column_stack((one, two))

======one
[0 1]
======two
[2 3]
===row_stack one, two
[[0 1]
 [2 3]]
===column_stack one, two
[[0 2]
 [1 3]]


In [35]:
a = arange(9).reshape(3,3)
print "=====a\n",a
print "=====hsplit(a,3)\n", hsplit(a,3)
print "=====split(a, 3, axis=1)\n", split(a, 3, axis = 1)

=====a
[[0 1 2]
 [3 4 5]
 [6 7 8]]
=====hsplit(a,3)
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
=====split(a, 3, axis=1)
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [37]:
print dict([(x,x*10) for x in range(100)])

{0: 0, 1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60, 7: 70, 8: 80, 9: 90, 10: 100, 11: 110, 12: 120, 13: 130, 14: 140, 15: 150, 16: 160, 17: 170, 18: 180, 19: 190, 20: 200, 21: 210, 22: 220, 23: 230, 24: 240, 25: 250, 26: 260, 27: 270, 28: 280, 29: 290, 30: 300, 31: 310, 32: 320, 33: 330, 34: 340, 35: 350, 36: 360, 37: 370, 38: 380, 39: 390, 40: 400, 41: 410, 42: 420, 43: 430, 44: 440, 45: 450, 46: 460, 47: 470, 48: 480, 49: 490, 50: 500, 51: 510, 52: 520, 53: 530, 54: 540, 55: 550, 56: 560, 57: 570, 58: 580, 59: 590, 60: 600, 61: 610, 62: 620, 63: 630, 64: 640, 65: 650, 66: 660, 67: 670, 68: 680, 69: 690, 70: 700, 71: 710, 72: 720, 73: 730, 74: 740, 75: 750, 76: 760, 77: 770, 78: 780, 79: 790, 80: 800, 81: 810, 82: 820, 83: 830, 84: 840, 85: 850, 86: 860, 87: 870, 88: 880, 89: 890, 90: 900, 91: 910, 92: 920, 93: 930, 94: 940, 95: 950, 96: 960, 97: 970, 98: 980, 99: 990}


In [38]:
print np.random

NameError: name 'np' is not defined

In [40]:
print random.random((2,2))

[[ 0.45853835  0.91483316]
 [ 0.63231661  0.60807451]]


In [42]:
v = array([1,2,3])  # v has shape (3,)
w = array([4,5])    # w has shape (2,)
v.reshape(3,1) * w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])